{% set name = "mapwidget" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mapwidget-{{ version }}.tar.gz
  sha256: 6cf82c99214673a9dd22c8231cc5d54083dc5e3a8204d8d33ee9d872bf4cf21c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - anywidget
    - xyzservices

test:
  imports:
    - mapwidget
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/giswqs/mapwidget
  summary: Custom Jupyter widgets for creating interactive maps
  license: MIT
  license_file: LICENSE
  description: Custom Jupyter widgets for creating interactive maps with popular JavaScript mapping libraries, such as Cesium, Mapbox, MapLibre, Leaflet, and OpenLayers.
  doc_url: https://mapwidget.gishub.org
  dev_url: https://github.com/giswqs/mapwidget

extra:
  recipe-maintainers:
    - giswqs
